version: '3.8'

services:
  rails_key_rotator:
    container_name: rails_key_rotator
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - history:/usr/local/hist
    environment:
      HISTFILE: /usr/local/hist/.bash_history
      IRB_HISTFILE: /usr/local/hist/.irb_history

volumes:
  bundle:
  history:
    external: true
    name: rails_key_rotator-history
